# docker build -f DockerFile . -t nightrang3r/langflow:latest
# docker run -d --add-host=host.docker.internal:host-gateway -p 7860:7860 -it --name langflow langflow:latest

FROM python:3.11.9-slim
RUN apt-get update 
RUN pip install langflow
ENV LANGFLOW_HOST=0.0.0.0
EXPOSE 7860
# Run langflow when the container launches
CMD ["langflow", "run"]
